import Layout from "../components/Layout";
import Link from "next/link";
import StrikeThroughHeader from "../components/StrikeThroughHeader";
import theme from "../theme";

const StoryTime = () => {
  return (
    <section>
      <div id="story">
        <div id="campfire" />
        <div id="hwrap">
          <h1>
            Story
            <br />
            Time
          </h1>
        </div>
      </div>
      <div className="row">
        <p>
          After working on a number of independent films with a lot of the same
          crew a group of us began to talk about the projects WE wanted to
          produce – and against all odds, we made some of them happen!
          <br />
          <br />
          While we weren’t getting paid, the camaraderie on set was palpable and
          we wanted what we made to be excellent so we didn’t mind the long
          hours, surviving off of fast food, or if it took a few too many takes
          to get it right – we were committed!
        </p>
        <p id="middle">
          While we weren’t getting paid, the camaraderie on set was palpable and
          we wanted what we made to be excellent so we didn’t mind the long
          hours, surviving off of fast food, or if it took a few too many takes
          to get it right – we were committed!
          <br />
          <br />
          I made a few observations:
          <br />
          <br />
          1. It seemed like most of the project concepts we took on were
          generated by the same few people.
          <br />
          <br />
        </p>

        <p>
          2. Some individuals talked about amazing projects they envisioned but
          they never brought it into production.
          <br />
          <br />
          3. Without the traditional production infrastructure, the lack of
          structure and consistency in terms of authority or accountability
          usually led to conflict.
        </p>
      </div>
      <img src="./solo-cowboy.jpg" />
      <style jsx>
        {`
          p {
            flex: 1;
          }
          img {
            width: 60vw;
            align-self: start;
            margin-top: -1rem;
            padding-left: 4rem;
            margin-bottom: -1rem;
          }
          #story {
            margin-top: -8rem;
            padding-left: 2rem;
            display: flex;
            flex-direction: row;
            align-items: center;
            width: 100%;
            margin-bottom: 2rem;
          }
          #campfire {
            flex: 2;
            background-image: url("./campfire.jpg");
            background-position: center;
            background-repeat: no-repeat;
            height: 20rem;
          }
          #middle {
            padding-right: 2rem;
            padding-left: 2rem;
          }
          h1 {
            font-size: 5rem;
            color: white;
            text-shadow: -3px -3px 0px ${theme.dark2};
            margin-left: -2rem;
          }
          #hwrap {
            flex: 1;
            background-color: ${theme.tan3rgba};
            border: 2px solid ${theme.dark2};
            padding-top: 2rem;
            padding-bottom: 2rem;
            margin-left: -4rem;
            margin-right: 2rem;
          }
          .row {
            display: flex;
            flex-direction: row;
            background-color: ${theme.tan2rgba};
            padding-right: 2rem;
            padding-left: 2rem;
          }
          section {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            padding: 0 4rem;
            font-size: 1.25rem;
            background-image: url("./wood-sand.jpg");
            background-position: center;
            background-repeat: no-repeat;
            margin-top: 8rem;
            margin-bottom: 8rem;
          }
          .content {
          }
        `}
      </style>
    </section>
  );
};

const PartTwo = () => {
  return (
    <section>
      <StrikeThroughHeader color="white" offset={3.2}>
        <h1>PT II</h1>
      </StrikeThroughHeader>
      <div className="row">
        <p>
          From being in community with creatives for years, I've done many jobs
          for free. Some because I like the person who's asking me, some because
          I am inspired by the project, and others to gain hopeful favors for
          future projects of my own.
        </p>
        <p id="middle">
          I started imagining what it would look like if I created a currency
          system for these "favors" - would the whole “asking someone to work
          for free” trend go away?
        </p>
        <p>
          What if there was a format? A structure? A framework that would take
          care of people and ideas and help them grow? And THEN once the project
          was ready, bring on the right team to help execute.
        </p>
      </div>
      <StrikeThroughHeader color="white"> </StrikeThroughHeader>

      <style jsx>
        {`
          section {
            font-size: 1.25rem;
            color: white;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            background-image: url("./wet-rocks.jpg");
            background-position: center;
            background-size: 100% auto;
            background-repeat: no-repeat;
          }
          p {
            flex: 1;
            padding-right: 2rem;
          }

          p:nth-child(1) {
            margin-top: -7rem;
          }

          p:nth-child(3) {
            margin-top: 7.5rem;
            margin-bottom: -7.5rem;
          }
          .row {
            display: flex;
            flex-direction: row;
            padding-left: 2rem;
            padding-top: 2rem;
            padding-bottom: 2rem;
          }
          h1 {
            font-size: 5rem;
          }
        `}
      </style>
    </section>
  );
};

const PartThree = () => {
  return (
    <section id="mission">
      <div className="row">
        <p className="border">
          So here we are: AGENCY HOUSE – A place for creators to grow, inspire
          and challenge each other – and bring potential projects into reality.
        </p>
        <div id="spacer" />
        <p>
          1. By making a platform where individuals can bring AGENCY to their
          visions and align/partner with others.
          <br />
          <br />
          2. By cultivating creators in order to give AGENCY to individuals and
          develop concepts/projects.
          <br />
          <br />
          3. By providing structure, accountability, and a lifeline to give
          AGENCY to all parties involved in bringing a passion project to life.
        </p>
      </div>

      <style jsx>
        {`
          .row {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 0 4rem;
            background-color: ${theme.tan1};
          }

          .border {
            border: 2px solid ${theme.dark2};
            padding: 2rem;
          }

          p {
            flex: 0.25;
          }

          p:nth-child(3) {
            margin-top: -4rem;
            margin-bottom: -4rem;
          }

          #spacer {
            flex: 0.1;
          }
          section {
            font-size: 1.5rem;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
          }
        `}
      </style>
    </section>
  );
};

const Story = () => {
  return (
    <Layout>
      <main>
        <StoryTime />
        <PartTwo />
        <PartThree />
      </main>
      <style jsx>{`
        main {
          display: flex;
          flex-direction: column;
          min-height: calc(100vh - 133px);
          width: 100vw;
        }
      `}</style>
    </Layout>
  );
};

export default Story;
